runtime: java11
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling: 
  instances: 1
health_check:
  enable_health_check: False
entrypoint: java -noverify -jar gameboard-0.0.1-SNAPSHOT.jar