# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ frontend ]
  pull_request:
    branches: [ frontend ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend/gameboard_front
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: master
        
    - run: flutter channel master
      working-directory: ${{env.working-directory}}
      
    - run: flutter upgrade
      working-directory: ${{env.working-directory}}
      
    - run: flutter config --enable-web
      working-directory: ${{env.working-directory}}
    
    - run: flutter clean
      working-directory: ${{env.working-directory}}
      
    - run: flutter pub get
      working-directory: ${{env.working-directory}}
      
    - run: flutter build
      working-directory: ${{env.working-directory}}
      

        
        
          echo Add other actions to build,
          echo test, and deploy your project.
